baseurl      = "http://josde.me/"
title        = "Josde's Homepage"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  # Subtitle for home
  homeSubtitle = "Welcome to my random code musings!"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Josde's Blog"
  keywords = "homepage, blog"
  images = [""]


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "josde.me"
    subtitle = "Josde's Coding Adventures"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "josde.me"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
    [[params.social]]
     name = "github"
     url = "https://github.com/Josde"
    [[params.social]]
      name = "twitch"
      url = "https://twitch.tv/Josde_"
    [[params.social]]
      name = "discord"
      url = "/discord"
    [[params.social]]
      name = "email"
      url = "https://secretstash.herokuapp.com/#!/show/b30f8a72c45181386aa521d404ec9bcf73d1c53b77996b93a3bd9afa10059c71"
    [[params.social]]
      name = "paypal"
      url = "https://paypal.me/itsJosde"



  # And you can even create generic menu
  [[menu.main]]
    identifier = "Posts"
    name       = "Posts"
    url        = "/posts"
  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url = "/resume"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url = "/projects"
