baseurl      = "https://dospuntostr.es/"
title        = ":3"
languageCode = "en-us"
theme        = "hello-friend-ng"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"
  # Subtitle for home

  enableRobotsTXT = true
  enableEmoji     = true
  enableMissingTranslationPlaceholders = true
  enableThemeToggle = true
  enableGlobalLanguageMenu = true
  canonifyURLs = true

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  
  images = [""]

[pagination]
  pagerSize = 10

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


[[params.social]]
  name = "github"
  url = "https://github.com/minipps"
[[params.social]]
  name = "email"
  url = "mailto:contact@dospuntostr.es"
[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/josde/"


# Internationalization


defaultContentLanguage = 'en'

[languages]
  [languages.en.params]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
    title = ":3"
    homeSubtitle = "Thoughts on technology and a few coding adventures ٩(◕‿◕｡)۶"
    subtitle = "dospuntostr.es"
    description = "A place where you will find my thoughts on ethics on technology, computer science and some random programming adventures."
    keywords = "blog, technology, programming, dospuntostr.es, josde, josde.me, :3, computer science, ethics"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "dospuntostr.es"
      logoHomeLink = "/"

      [[languages.en.menu.main]]
        identifier = "Musings"
        name       = "Musings"
        url        = "/post/"
      [[languages.en.menu.main]]
        identifier = "resume"
        name       = "Resume"
        url = "/resume/"

      [[languages.en.menu.main]]
        identifier = "projects"
        name       = "Projects"
        url = "/projects/"

   [languages.es.params]
    disabled = false
    languageCode = 'es-ES'
    languageDirection = 'ltr'
    languageName = 'Español'
    homeSubtitle = "Reflexiones sobre tecnología y aventuras de programación ٩(◕‿◕｡)۶"
    title = ":3"
    subtitle = 'dospuntostr.es'
    description = "El blog de mini. Un lugar donde encontrarás reflexiones sobre la ética en la tecnología y en la ingeniería informática, además de aventuras aleatorias de programación."
    keywords = "blog, tecnología, programación, josde, josde.me, etica, ingeniería informática, tecnología humana"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Leer otros posts"
    weight = 2
    [languages.es.params.logo]
        logoText = "dospuntostr.es"
        logoHomeLink = "/"

    [[languages.es.menu.main]]
      identifier = "musings"
      name       = "Desvaríos"
      url        = "/es/post/"

    [[languages.es.menu.main]]
      identifier = "resume"
      name       = "Currículum"
      url = "/es/resume/"
    [[languages.es.menu.main]]
      identifier = "projects"
      name       = "Proyectos"
      url = "/es/projects/"

[params.footer]
    trademark = false
    rss = true
    copyright = false
    author = false
    human_made = true
    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a> and <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">hello-friend-ng</a>",
      "Articles written with &#10084 by mini"
    ]

[params.author]
    name = "mini"
    email = "contact@dospuntostr.es"

