baseurl      = "https://josde.me/"
title        = "Josde's Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"
  # Subtitle for home

  enableRobotsTXT = true
  enableEmoji     = true
  enableMissingTranslationPlaceholders = true
  enableThemeToggle = true
  enableGlobalLanguageMenu = true
  canonifyURLs = true

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  
  images = [""]


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


[[params.social]]
  name = "github"
  url = "https://github.com/Josde"
[[params.social]]
  name = "twitch"
  url = "https://twitch.tv/Josde_"
[[params.social]]
  name = "discord"
  url = "https://discord.com/invite/sXV9KMgd"
[[params.social]]
  name = "email"
  url = "mailto:contact@josde.me"
[[params.social]]
  name = "paypal"
  url = "https://paypal.me/itsJosde"
[[params.social]]
  name = "mastodon"
  url = "https://owo.cafe/@Josde"
[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/jorge-cruz-garc%C3%ADa-9a6882196/"

# And you can even create generic menu
[[menu.main]]
  identifier = "Musings"
  name       = "Musings"
  url        = "/post/"
[[menu.main]]
  identifier = "resume"
  name       = "Resume"
  url = "/resume/"

[[menu.main]]
  identifier = "projects"
  name       = "Projects"
  url = "/projects/"

# Internationalization


defaultContentLanguage = 'en'

[languages]
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
    title = "Josde's Random Musings"
    homeSubtitle = "Thoughts on technology and a few coding adventures ٩(◕‿◕｡)۶"
    subtitle = "josde.me"
    description = "Josde's Blog. A place where you will find my thoughts on ethics on technology, computer science and some random programming adventures."
    keywords = "blog, technology, programming, josde, josde.me, computer science, ethics"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "josde.me"
      logoHomeLink = "/"
   [languages.es]
    disabled = false
    languageCode = 'es-ES'
    languageDirection = 'ltr'
    languageName = 'Español'
    homeSubtitle = "Reflexiones sobre tecnología y aventuras de programación ٩(◕‿◕｡)۶"
    title = "Las movidas aleatorias de Josde"
    subtitle = 'josde.me'
    description = "El blog de Josde. Un lugar donde encontrarás reflexiones sobre la ética en la tecnología y en la ingeniería informática, además de aventuras aleatorias de programación."
    keywords = "blog, tecnología, programación, josde, josde.me, etica, ingeniería informática, tecnología humana"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Leer otros posts"
    weight = 2
    [languages.es.params.logo]
        logoText = "josde.me"
        logoHomeLink = "/"


[params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a> and <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">hello-friend-ng</a>",
      "Articles written with &#10084 by Josde"
    ]

[author]
    name = "Josde"
    email = "contact@josde.me"